version: "3.8"

services:
  streaming_preprocess:
    container_name: streaming_preprocess
    build:
      context: streaming_preprocess
    image: streaming_preprocess
    expose:
      - 3000
      - 4000
    depends_on:
      - streaming_pipeline
    networks:
      goodganglabs:
        ipv4_address: ${PREPROCESS_HOST}
    env_file:
      - .env
    restart: always

  streaming_postprocess:
    container_name: streaming_postprocess
    build:
      context: streaming_postprocess
    image: streaming_postprocess
    expose:
      - 5000
    depends_on:
      - streaming_pipeline
    networks:
      goodganglabs:
        ipv4_address: ${POSTPROCESS_HOST}
    env_file:
      - .env
    restart: always

  streaming_deep_learning:
    container_name: streaming_deep_learning
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning
    depends_on:
      - streaming_pipeline
    networks:
      goodganglabs:
        ipv4_address: ${DEEP_LEARNING_HOST}
    env_file:
      - .env
    restart: always

  streaming_pipeline:
    container_name: streaming_pipeline
    image: redis:7.0.7-alpine
    expose:
      - 6379
    networks:
      goodganglabs:
        ipv4_address: ${REDIS_HOST}
    restart: always

  streaming_router:
    container_name: streaming_router
    build:
      context: streaming_router
    image: streaming_router
    ports:
      - 80:80
      - 443:80
      - 4000:4000
      - 5000:5000
    networks:
      goodganglabs:
        ipv4_address: ${NGINX_HOST}
    env_file:
      - .env
    restart: always

networks:
  goodganglabs:
    name: goodganglabs
    ipam:
      driver: default
      config:
        - subnet: ${DEFAULT_SUBNET}
        - gateway: ${DEFAULT_GATEWAY}
