version: "3.8"

services:
  streaming_proxy:
    container_name: streaming_proxy
    build:
      context: streaming_proxy
    image: streaming_proxy
    expose:
      - 3000
      - 4000
    depends_on:
      - streaming_cache_store
    networks:
      goodganglabs:
        ipv4_address: ${PREPROCESS_HOST}
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always

  streaming_inference1:
    container_name: streaming_inference1
    build:
      context: streaming_inference
    image: streaming_inference1
    expose:
      - 50051
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.7
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always

  streaming_inference2:
    container_name: streaming_inference2
    build:
      context: streaming_inference
    image: streaming_inference2
    expose:
      - 50051
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.8
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always

  streaming_inference3:
    container_name: streaming_inference3
    build:
      context: streaming_inference
    image: streaming_inference3
    expose:
      - 50051
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.9
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always
  
  streaming_inference4:
    container_name: streaming_inference4
    build:
      context: streaming_inference
    image: streaming_inference4
    expose:
      - 50051
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.10
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always

  streaming_inference5:
    container_name: streaming_inference5
    build:
      context: streaming_inference
    image: streaming_inference5
    expose:
      - 50051
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.11
    volumes:
      - ./grpc:/usr/local/grpc
    env_file:
      - .env
    restart: always

  streaming_cache_store:
    container_name: streaming_cache_store
    image: redis:7.0.7-alpine
    expose:
      - 6379
    networks:
      goodganglabs:
        ipv4_address: ${REDIS_HOST}
    restart: always

  streaming_router:
    container_name: streaming_router
    build:
      context: streaming_router
    image: streaming_router
    ports:
      - 80:80
      - 443:80
    depends_on:
      - streaming_proxy
    networks:
      goodganglabs:
        ipv4_address: ${NGINX_HOST}
    restart: always

networks:
  goodganglabs:
    name: goodganglabs
    ipam:
      driver: default
      config:
        - subnet: ${DEFAULT_SUBNET}
          gateway: ${DEFAULT_GATEWAY}
