version: "3.8"

services:
  streaming_preprocess:
    container_name: streaming_preprocess
    build:
      context: streaming_preprocess
    image: streaming_preprocess
    expose:
      - 3000
      - 4000
    depends_on:
      streaming_pipeline:
        condition: service_healthy
      streaming_cache_store:
        condition: service_started
    networks:
      goodganglabs:
        ipv4_address: ${PREPROCESS_HOST}
    env_file:
      - .env
    restart: always

  streaming_postprocess:
    container_name: streaming_postprocess
    build:
      context: streaming_postprocess
    image: streaming_postprocess
    expose:
      - 5000
    depends_on:
      streaming_pipeline:
        condition: service_healthy
      streaming_cache_store:
        condition: service_started
    networks:
      goodganglabs:
        ipv4_address: ${POSTPROCESS_HOST}
    env_file:
      - .env
    restart: always

  streaming_deep_learning1:
    container_name: streaming_deep_learning1
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning1
    depends_on:
      streaming_pipeline:
        condition: service_healthy
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.7
    env_file:
      - .env
    restart: always

  streaming_deep_learning2:
    container_name: streaming_deep_learning2
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning2
    depends_on:
      streaming_pipeline:
        condition: service_healthy
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.8
    env_file:
      - .env
    restart: always

  streaming_deep_learning3:
    container_name: streaming_deep_learning3
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning3
    depends_on:
      streaming_pipeline:
        condition: service_healthy
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.9
    env_file:
      - .env
    restart: always

  streaming_deep_learning4:
    container_name: streaming_deep_learning4
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning4
    depends_on:
      streaming_pipeline:
        condition: service_healthy
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
    restart: always

  streaming_deep_learning5:
    container_name: streaming_deep_learning5
    build:
      context: streaming_deep_learning
    image: streaming_deep_learning5
    depends_on:
      streaming_pipeline:
        condition: service_healthy
    networks:
      goodganglabs:
        ipv4_address: 172.20.0.11
    env_file:
      - .env
    restart: always

  streaming_cache_store:
    container_name: streaming_cache_store
    image: redis:7.0.7-alpine
    expose:
      - 6379
    networks:
      goodganglabs:
        ipv4_address: ${REDIS_HOST}
    restart: always
  
  streaming_pipeline:
    container_name: streaming_pipeline
    build:
      context: streaming_pipeline
    image: streaming_pipeline
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      goodganglabs:
        ipv4_address: ${RABBITMQ_HOST}
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 10s
        retries: 5
    restart: always

  streaming_router:
    container_name: streaming_router
    build:
      context: streaming_router
    image: streaming_router
    ports:
      - 80:80
      - 443:80
    depends_on:
      - streaming_preprocess
      - streaming_postprocess
    networks:
      goodganglabs:
        ipv4_address: ${NGINX_HOST}
    restart: always

networks:
  goodganglabs:
    name: goodganglabs
    ipam:
      driver: default
      config:
        - subnet: ${DEFAULT_SUBNET}
          gateway: ${DEFAULT_GATEWAY}
