# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"w\n\rStreamRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x05\x12\x11\n\tstartedAt\x18\x03 \x01(\x05\x12\r\n\x05\x66rame\x18\x04 \x03(\x0c\x12\x11\n\ttimestamp\x18\x05 \x03(\x05\x12\x0c\n\x04step\x18\x06 \x03(\x05\"\x13\n\x11InferenceResponse2@\n\tInference\x12\x33\n\x0bInputStream\x12\x0e.StreamRequest\x1a\x12.InferenceResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMREQUEST._serialized_start=19
  _STREAMREQUEST._serialized_end=138
  _INFERENCERESPONSE._serialized_start=140
  _INFERENCERESPONSE._serialized_end=159
  _INFERENCE._serialized_start=161
  _INFERENCE._serialized_end=225
# @@protoc_insertion_point(module_scope)
